// GOOGLE CALENDAR WEBHOOK EVENTS
export const GOOGLE_CALENDAR_EVENT_PROCESSOR =
  'GOOGLE_CALENDAR_EVENT_PROCESSOR';
export const GOOGLE_CALENDAR_PUSH_EVENTS = 'GOOGLE_CALENDAR_PUSH_EVENTS';

export const GOOGLE_CALENDAR_DELETE_EVENTS = 'GOOGLE_CALENDAR_DELETE_EVENTS';
